---
title: "Sankey"
author: "Jesus Alvarado Valverde"
date: "2022-12-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r MotifMatches_table,echo = FALSE}
library(tidyverse)
library(gridExtra)
library(ggplot2)
library(knitr) 

MotifHits_filt<-read_tsv(file="/ALIAS_MotifMatches_filtered.tsv", col_names = T)
```

```{R Sankey 1, echo=FALSE}
library(devtools)
library(gridExtra)
# save the widget
library(htmlwidgets)

# Libraries
library(viridis)
library(patchwork)
library(hrbrthemes)
library(circlize)
library(networkD3)

organelles<-c("micronemes","rhoptries","dense_granules")
types <- c("CLV","DEG","DOC","LIG","MOD","TRG")
secretion <- c("Secreted","NonSecreted","Other")


vals_df <- tibble(organelles=organelles)

vals_1 <- c()
c=1
for(i in 1:3){
  for(j in 1:6){
    hits <- MotifHits %>% filter(Organelle==organelles[i] & Motif_Type==types[j]) %>% nrow()
    vals_1[c] <- hits
    c <-  c + 1
  }
}

vals_2 <- c()

c=1
for(i in 1:3){
  for(j in 1:6){
    hits <- MotifHits_filt %>% filter(Organelle==organelles[i] & Motif_Type==types[j]) %>% nrow()
    vals_2[c] <- hits
    c <-  c + 1
  }
}

organelles<-c("Micronemes","Rhoptries","Dense granules")
data_long<-data.frame(ORG=rep(organelles, times=c(6,6,6)), TY=rep(types, times=3),values=vals_1)
data_long<-data.frame(ORG=rep(organelles, times=c(6,6,6)), TY=rep(types, times=3),values=vals_2)

data_long <- data_long %>% filter(values>0)
nodes <- data.frame(name=c(as.character(data_long$ORG), as.character(data_long$TY)) %>% unique())

data_long$IDsource=match(data_long$ORG, nodes$name)-1
data_long$IDtarget=match(data_long$TY, nodes$name)-1

ColourScal ='d3.scaleOrdinal() .range(["#FED756","#8DB7E2", "#70BF4A", "#734595","#A1BE1F", "#F49E17", "#3B6FB6", "#D41645","#F4C61F"])'

p1<-sankeyNetwork(Links = data_long, Nodes = nodes,
                    Source = "IDsource", Target = "IDtarget",
                    Value = "values", NodeID = "name", 
                    sinksRight=FALSE, colourScale=ColourScal, 
                    nodeWidth=50, nodePadding=30,
                    fontSize=20, fontFamily = 'Cambria',
                    height = 500, width = 1000)
p1
saveWidget(p2_1, file=paste0( getwd(), "SLiM_Organelles_Bar_raw.html"))
saveWidget(p2_2, file=paste0( getwd(), "SLiM_Organelles_Bar_filt.html"))
```

```{R Sankey, echo=FALSE}
vals_3 <- c()

c=1
for(i in 1:3){
  for(j in 1:6){
    hits <- MotifHits_filt %>% filter(Secretion==secretion[i] & Motif_Type==types[j]) %>% nrow()
    vals_3[c] <- hits
    c <-  c + 1
  }
}

vals_df <- tibble(Secretion=secretion)

data_long<-data.frame(SEG=rep(secretion, times=c(6,6,6)), TY=rep(types, times=3),values=vals_3)

data_long <- data_long %>% filter(values>0)
nodes <- data.frame(name=c(as.character(data_long$SEG), as.character(data_long$TY)) %>% unique())

data_long$IDsource=match(data_long$SEG, nodes$name)-1
data_long$IDtarget=match(data_long$TY, nodes$name)-1

ColourScal ='d3.scaleOrdinal() .range(["#18974C", "darkgrey", "grey", "#734595","#A1BE1F", "#F49E17", "#3B6FB6", "#D41645","#F4C61F"])'


p2<-sankeyNetwork(Links = data_long, Nodes = nodes,
                    Source = "IDsource", Target = "IDtarget",
                    Value = "values", NodeID = "name", 
                    sinksRight=FALSE, colourScale=ColourScal, 
                    nodeWidth=50, nodePadding=30,
                    fontSize=20, fontFamily = 'Cambria',
                    height = 500, width = 1000)

p2



```

```{R}

```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
